### ISSUE TITLE
Can I safely use undocumented features?

### ISSUE THREAD

**Issue by cyber-chuvash** [aiokitchen/aiomisc#98]
Can I safely use undocumented features, such as `aiomisc.log.wrap.wrap_logging_handler()` in production? Is it a stable API with just a poor documentation coverage, or is it just internal stuff that might change at any time?

**Comment by mosquito** [comment]
Our team is doing everything to comply with all SemVer principles. And if some method is not described in the documentation, this is an imperfection of the documentation. You can count on the fact that if a function is not marked as "internal" in any way, its API will remain compatible according to all SemVer principles.

Unfortunately, there are very few volunteers willing to do the documentation for the project. We also do not always have time for this. First of all, this library was created for use in our team, it became Open Source, because at that time it decision was more flexible for us. 

The code quality and testing is the major points for us, unfortunately documentation is not best at this time, sorry for this.

If you would like to contribute to the documentation, we would greatly appreciate it.

**Comment by cyber-chuvash** [comment]
Thank you very much!
